### ISSUE TITLE
imageUrl is wrong

### ISSUE THREAD

**Issue by huzhenjie** [gpake/qiniu-wxapp-sdk#1]
Something wrong in `qiniu-wxapp-sdk/sdk/qiniuUploader.js`

line 89:
```
var imageUrl = config.qiniuImageURLPrefix + dataObject.key;
```

fix:
```
var imageUrl = 'http://' + config.qiniuImageURLPrefix + '/' + dataObject.key;
```

**Comment by gpake** [comment]
Hi @huzhenjie,
I prefer users write `domain: 'http://yourBucket.bkt.clouddn.com'` in the `qiniuUploader.init` function in case that qiniu changes the protocol like `https` or some user would use the `qnssl.com`.
Adding the `/` after prefix is a good idea, I've add it at bef4ef6c28aaf7457e1a8f12f31a111f765b81bc
