### ISSUE TITLE
上传成功了，图片显示失败是什么原因呢

### ISSUE THREAD

**Issue by codon19** [gpake/qiniu-wxapp-sdk#13]
VM5197:2 Failed to load image https://up.qbox.me/tmp_1791636906o6zAJsx-VQRa262QRItZhHXEVXG41f49994edcac6f74e3b8172e07934a9d.jpg : the server responded with a status of 405 (HTTP/1.1 405) 
From server 115.231.97.59

**Comment by gpake** [comment]
https://up.qbox.me 不是图片存储的域名，你应该使用你的 bucket 地址，长得样子类似于 https://ojpmadrlt.bkt.clouddn.com，把这个传入你的初始化参数，然后应该就可以了
你可以在你的七牛管理后台，存储空间部分找到

**Comment by codon19** [comment]
刚解决了，谢谢老铁
