### ISSUE TITLE
uptoken 可以本地生成吗

### ISSUE THREAD

**Issue by ZengTianShengZ** [gpake/qiniu-wxapp-sdk#15]
该 qiniu-wxapp-sdk 有提供本地生成 uptoken 的方法吗

**Comment by gpake** [comment]
可以尝试参考一下这个（#9），本地生成暂时不打算添加。
原文如下：
> 以七牛的建议来说，配合服务器分发 token 更安全一些，uptoken 的生成代码可以参考[七牛上传 token 文档](https://developer.qiniu.com/kodo/manual/1208/upload-token) 或者我朋友写的 [tiny-qiniu](https://github.com/die-welle/tiny-qiniu/blob/master/src/index.js)

**Comment by ZengTianShengZ** [comment]
好的，非常感谢，已经配合服务端使用了，很棒

**Comment by gpake** [comment]
客气了
