### ISSUE TITLE
qiniuUploader 文件 dataobject 值不对吧？

### ISSUE THREAD

**Issue by chenweigh** [gpake/qiniu-wxapp-sdk#20]
wx.uploadFile({
        url: url,
        filePath: filePath,
        name: 'file',
        formData: formData,
        success: function (res) {
          console.log(res);
          var dataString = res.data
          try {
            var dataObject = JSON.parse(dataString);
            //do something
            var imageUrl = config.qiniuImageURLPrefix + '/' + dataObject.key;
            dataObject.imageURL = imageUrl;
            console.log(dataObject);
            if (success) {
              success(dataObject);
            }
          } catch(e) {
            console.log('parse JSON failed, origin String is: ' + dataString)
            if (fail) {
              fail(e);
            }
          }
        },
        fail: function (error) {
            console.error(error);
            if (fail) {
                fail(error);
            }
        }
    })

----
dataObject 的值是这个样子的：
{error：{"callback_url":"https://app.cxy61.com/server/uplo…","key":"2ce1804bd11a8be137d0c18ef1399148_m.png"}", imageURL: "/undefined"}

直接取 dataobject.key是 undefined，还有一层 error？怎么回事？

**Comment by gpake** [comment]
暂时不确定，抱歉最近有些忙，如果可以的话，不妨帮忙 debug 一下？

**Comment by chenweigh** [comment]
Already solved, there is a problem with our server configuration.
