### ISSUE TITLE
请问可以获取图片 exif 信息吗

### ISSUE THREAD

**Issue by zenglincient** [gpake/qiniu-wxapp-sdk#26]
发现没有办法获取到图片的其他信息，想获取图片的exif

**Comment by gpake** [comment]
不好意思，这是七牛上传文件的库，不打算做这方面的功能。
如果需要获取 exif，不妨看看 [exif-js](https://github.com/exif-js/exif-js) 之类的。
ps: 我并没有使用过上面这个库
