### ISSUE TITLE
华东区域名，上传图片返参格式不对

### ISSUE THREAD

**Issue by ZhaZhengRefn** [gpake/qiniu-wxapp-sdk#28]
![image](https://user-images.githubusercontent.com/16488686/37380569-3fd5c040-2774-11e8-9814-25cf0197e093.png)
而库中对应的是：
![image](https://user-images.githubusercontent.com/16488686/37380594-51fa176c-2774-11e8-81c2-982493494f00.png)

**Comment by ZhaZhengRefn** [comment]
解决了。七牛返回了一段unicode值。
![image](https://user-images.githubusercontent.com/16488686/37387271-b6274e90-2796-11e8-8b41-aef73d3cd408.png)

**Comment by gpake** [comment]
请问什么情况下不返回 json 而是 unicode？
