### ISSUE TITLE
uploadImage

### ISSUE THREAD

**Issue by GrapeFruitJun** [gpake/qiniu-wxapp-sdk#3]
uploadFile:fail exceed max upload connection count 1

**Comment by gpake** [comment]
Hi @GrapeFruitJun,
It seems because that you are trying to upload too more images one time and killed by wxapp api, try to call upload after one finished.
And I'm trying to add a upload queue.

**Comment by GrapeFruitJun** [comment]
but i just upload one pic, so i don't know why

**Comment by gpake** [comment]
I've tested the demo, it works well.
try to disable other network request before upload.
and log the upload task in case there is a bug

**Comment by GrapeFruitJun** [comment]
Thank you for your help, looking forward to your new version with  upload queue , it will help a lot of people

**Comment by gpake** [comment]
@GrapeFruitJun so is there a bug that caused upload called more than once?

**Comment by GrapeFruitJun** [comment]
nope

**Comment by gpake** [comment]
你在 sdk 里面打 log，看看 upload 到底被调用了几次。或者打断点也行，顺便看看调用栈。还有问题继续留言。
