### ISSUE TITLE
上传类型

### ISSUE THREAD

**Issue by HarrylXue** [gpake/qiniu-wxapp-sdk#31]
请问这个sdk不支持上传视频么，上传视频调用这个sdk不成功

**Comment by gpake** [comment]
刚测试成功，使用[chooseVideo](https://mp.weixin.qq.com/debug/wxadoc/dev/api/media-video.html#wxchoosevideoobject)。
请问你的报错是怎样的

**Comment by HarrylXue** [comment]
uploadFile:fail file path invalid
pathFile 重新定义下搞定了，谢谢
