### ISSUE TITLE
ucwords() expects exactly 1 parameter, 2 given

### ISSUE THREAD

**Issue by AdBrandon** [gpake/qiniu-wxapp-sdk#32]
[2] ErrorException in Client.php line 132

private static function parseHeaders($raw)
    {
        $headers = array();
        $headerLines = explode("\r\n", $raw);
        foreach ($headerLines as $line) {
            $headerLine = trim($line);
            $kv = explode(':', $headerLine);
            if (count($kv) > 1) {
                $kv[0] = ucwords($kv[0], '-');
                $headers[$kv[0]] = trim($kv[1]);
            }
        }
        return $headers;
    }
部署的时候更新了一直报错，还以为是权限问题。。。

**Comment by gpake** [comment]
不好意思，我不太清楚 php sdk 的实现，麻烦去对应的地方提交 issue
