### ISSUE TITLE
debug模式下才能上传图片；把调试模式关了以后，无法上传

### ISSUE THREAD

**Issue by unionTime** [gpake/qiniu-wxapp-sdk#35]
iOS:11.2.6
微信版本：6.6.5
基础库：1.9.94

debug模式无法上传，这个是问题呢。自己的服务器是可以连接的，https已经配置

**Comment by gpake** [comment]
1. debug 模式到底是可以上传，还是无法上传？
2. 有什么报错信息？

**Comment by unionTime** [comment]
@gpake 开启调式模式是可以正常上传的，关掉后就无法上传，然后也看不到信息。我想个办法，看看有没有什么报错。

**Comment by unionTime** [comment]
@gpake 找到报错信息了！
{"errMsg':"uploadFile:fail url not in domain list"}

是不是我的存储区域对应 HTTPS 地址的问题：
我的是华南区，
我写了http(s)://upload-z2.qiniup.com，而不是https://up-z2.qbox.me
是不是这个原因，感谢！

**Comment by gpake** [comment]
SDK 内部使用的是qbox.me 的老域名，暂时没有看到有什么问题。
域名设置请参照文档。

或者，也可以手动修改 sdk 中的 url。

**Comment by jawQ** [comment]
我也有同样的问题出现，我是：https://up-z2.qbox.me，也还是报：{"errMsg':"uploadFile:fail url not in domain list"}

**Comment by gpake** [comment]
搜到一个可能性 「uploadFile配置合法域名的时候弄错了 把七牛的那个域名配置上去就ok了 」
参见：[关于文件上传问题wx.upload() 在真机上测试上传功能返回错误](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=4e665eb5b0048d5849cf595b9d56c115)

**Comment by jawQ** [comment]
不太明白，“七牛云的那个域名”？？原本配置的是关于地域的域名，还是说是访问图片资源的域名？

**Comment by gpake** [comment]
小程序后台需要提前配置域名，上传下载都需要先配置，才能在非 debug 模式下访问到相关服务器。
需要填写的内容请看 [readme：准备](https://github.com/gpake/qiniu-wxapp-sdk#%E5%87%86%E5%A4%87) ：

> 根据你创建的七牛存储空间，把对应的 https 上传地址添加到小程序的访问白名单中，方法如下：
> 
> > 登录 微信公众平台，前往 设置 - 开发设置，点击 服务器配置 下的「修改」链接。
> > 修改 uploadFile 域名(比如华北 https 上传地址为：https://up-z1.qbox.me，地址不清楚请参见https地址附录)
> > 如果需要下载文件，则还需要一同设置 downloadFile 域名，为你的 bucket 下载地址
> > 保存即可
> 
> 字段名 | 内容
> -- | --
> request 域名 | https://yourServce.com
> uploadFile 域名 | https://up.qbox.me （根据存储区域填写）
> downloadFile 域名 | https://baldkf.bkt.clouddn.com

**Comment by jawQ** [comment]
关键地址已经配了，就是根据区域来配的，然后就出现上面提到的问题了。

**Comment by fiasco-zh** [comment]
我也遇到了，折腾了半天终于解决了。 qiniuUploader.js里搜 qbox.me。把你所在的区域的uploadURL改成和小程序后台配置的一样就行了。
我用的华东，对应的是'ECN'，我的都改成了 ’https://upload.qiniup.com‘ （官网上提供的，可能是新的），现在手机预览可以传图了

**Comment by gpake** [comment]
明白，需要确认一下原有域名是否继续有效的问题。

**Comment by woodccc** [comment]
@fiasco-zh 谢谢，帮助很大，已解决。

**Comment by gpake** [comment]
b546064c775f0231898d8bfa2f219f786aab3d37 已经修复了域名问题，不好意思各位，这么久才修复。
