### ISSUE TITLE
七牛上传图片 私有图片 返回有错。

### ISSUE THREAD

**Issue by ticktack** [gpake/qiniu-wxapp-sdk#36]
console.group("Tue Apr 03 2018 18:23:21 GMT+0800 (中国标准时间) 渲染层网络层错误")
          console.error(`Failed to load image http://happydays.qiniudn.com/tmp/wxfebb357a0ab8b143.o6zAJs_E5Dqkdwcjww9r3DfkV0Tk.eihfcZD21WSv0af563fc64b50a28a58711ff280d0bb0.png
the server responded with a status of 401 (HTTP/1.1 401 Unauthorized) 
From server 110.88.145.97`)
        console.groupEnd()

**Comment by gpake** [comment]
401应该是权限错误，你可以尝试检查一下 token 是否正确
以及，上面的 url 访问直接报错：`error: "download token not specified"`

**Comment by ZhangYi0415** [comment]
私有空间需要解密后的地址，你这个地址格式不对啊。得看下七牛读取私密空间图片的说明文档
