### ISSUE TITLE
(小程序 ) uptoken 设置了，但是请求接口时，参数没带上去！

### ISSUE THREAD

**Issue by proc07** [gpake/qiniu-wxapp-sdk#38]
![image](https://user-images.githubusercontent.com/16809535/39660394-8de6bd82-5070-11e8-92c8-aed377fc4278.png)
![image](https://user-images.githubusercontent.com/16809535/39660396-956e376a-5070-11e8-8a5a-0926b06f4309.png)
![image](https://user-images.githubusercontent.com/16809535/39660399-9aad9982-5070-11e8-89f4-e1d9160395bb.png)

**Comment by CoXier** [comment]
+1

**Comment by gpake** [comment]
刚测试了一下，您的写法 token 是可以直接带到上传表单中的，请检查这个 token 是否有效

**Comment by CoXier** [comment]
应该是 token 的问题。
