### ISSUE TITLE
关于key的问题

### ISSUE THREAD

**Issue by hosven** [gpake/qiniu-wxapp-sdk#4]
qiniu的默认是：不设置key时，自动生成qiniu的etag来作为key，可以消重。
请问这个sdk要修改哪里才能达到这种效果。

如果按现在的默认设置使用微信的filepath来做key的话，就无法在qiniu消重了。

非常感谢

**Comment by hosven** [comment]
找到了！
将这个'key'注释掉

var formData = {
        'token': config.qiniuUploadToken,
        // 'key': fileName
    };

**Comment by gpake** [comment]
多谢提醒，我没有考虑到这个问题。接下来加上

**Comment by gpake** [comment]
@hosven,
Hey 096146414e71a58dc98d8fcfa065657269fe637c there is my solution, a new key [shouldUseQiniuFileName: bool] in options to determine wechat filename or qiniu
