### ISSUE TITLE
上传的视频无法播放

### ISSUE THREAD

**Issue by wfz90** [gpake/qiniu-wxapp-sdk#41]
上传是成功的，小程序和浏览器都不能播放，但是可以下载来播放，好诡异

**Comment by gpake** [comment]
可以提供一个 url 看看？

**Comment by wfz90** [comment]
大佬请看一下， http://kanxiaodian-upload.shyohan.com/tmp/wxd49bb4da7911af4e.o6zAJszl92hXlOOv89qXmKZ7-c0U.bVqfOVUhXX4G07fd23a1752289f04ae53da781b4a259.mp4

这是用相机拍的，微信里的相机拍的也不行。

**Comment by gpake** [comment]
GET http://kanxiaodian-upload.shyohan.com/tmp/wxd49bb4da7911af4e.o6zAJszl92hXlOOv89qXmKZ7-c0U.bVqfOVUhXX4G07fd23a1752289f04ae53da781b4a259.mp4 403 (Forbidden)
??
看一眼 qiniu bucket 设置？

**Comment by wfz90** [comment]
但是这个链接可以下载，我刚刚试了小程序端又可以播放了，真是怪了

**Comment by gpake** [comment]
bucket 如果没有权限鉴定，应该不会遇到403。
小程序记得设置 url 白名单。
再测试测试，注意观察 console 的报错。

**Comment by wfz90** [comment]
好的好的，谢谢大佬，再观察下
