### ISSUE TITLE
按照项目demo操作，报了下面的错误

### ISSUE THREAD

**Issue by chenDiDi** [gpake/qiniu-wxapp-sdk#43]
在不校验域名的情况下：
![image](https://user-images.githubusercontent.com/19472038/42354386-12bbb3ba-80f9-11e8-922c-e42f9e571ca0.png)

![image](https://user-images.githubusercontent.com/19472038/42354390-1c5bd634-80f9-11e8-850b-59a716ec2796.png)

![image](https://user-images.githubusercontent.com/19472038/42354451-7ffe6742-80f9-11e8-8b9d-f5dfd35f594b.png)

后面多了个undefined?  请问会是什么导致这个问题，uptoken不正确？

**Comment by gpake** [comment]
看起来是说no such bucket，检查一下url参数？
报错后没处理好url，我后面修改一下

**Comment by chenDiDi** [comment]
![image](https://user-images.githubusercontent.com/19472038/42355969-70e2522e-8102-11e8-8a54-2d5a93305a5c.png)
报no such bucket的时候，后面会添加多了个undefined的，
这是我options配置的参数
![image](https://user-images.githubusercontent.com/19472038/42356012-9f3a5d24-8102-11e8-98f9-641b0e3369f3.png)

**Comment by gpake** [comment]
**0**, no such bucket 可能是生成 uptoken 的时候没带上正确的 bucket，不妨检查一下
**1**, undefined 是因为我没有判空，我后面修改一下
**2**, domain 的作用是：如果设置了，会在 success callback 的 res 参数加上可以直接使用的 ImageURL 字段，`res.imageURL = domain + res.fileURL`。和上传没有关系

**Comment by gpake** [comment]
@chenDiDi 可以麻烦确认一下问题么，希望这个 issue 可以持续的帮助其他人定位和解决问题，感谢
