### ISSUE TITLE
请问为什么上传的是文件，还会返回imageUrl

### ISSUE THREAD

**Issue by kajweb** [gpake/qiniu-wxapp-sdk#44]
为要上传的是m4a，acc等文件，。返回等imageUrl访问异常

**Comment by gpake** [comment]
最早的时候没考虑到上传文件的case，后面修改一下字段名

**Comment by gpake** [comment]
你说 imageUrl 访问异常是什么？

**Comment by kajweb** [comment]
已解决，。前后端配置不一致引起的。但是实际上返回还是url，没有提示报错。得出来的url无法访问。

**Comment by gpake** [comment]
我想知道 SDK 是否在这个 case 中表现出 bug，如果有应该如何修改？

**Comment by kajweb** [comment]
抱歉。七牛这块我现在不是很熟。

**Comment by kajweb** [comment]
等有空我研究下，再看看能不能pr

**Comment by gpake** [comment]
好的，十分感谢，如果没空提 pr，直接描述问题也是可以的

**Comment by nsnake** [comment]
这个imageUrl是SDK里面自己生成的。可以看107行的 
**var imageUrl = config.qiniuImageURLPrefix + '/' + dataObject.key;**
虽然这个拼接是好意，但容易引起误解。七牛本身在设置里就可以自定义返回字段的名称，如果以官方的名称去生成token则还好，如果是自定义的名称肯定是会出错的。 所以还不如把后继交给用户自己处理比较好

**Comment by gpake** [comment]
是的，这个字段是一个麻烦，打算干掉

**Comment by gpake** [comment]
@nsnake 额，直接使用 `res.key` 应该可以取到你想要的内容吧？upload 返回的 dataObject 我直接传给用户了，麻烦确认一下？
