### ISSUE TITLE
代码有个小问题

### ISSUE THREAD

**Issue by julyL** [gpake/qiniu-wxapp-sdk#49]
现在代码中只能在upload方法里面传key, 不能在init里面设置
```js
    // 问题代码
    if (options && options.key) {
        fileName = options.key;
    }
```
已pull request

**Comment by gpake** [comment]
这个 key，是作为文件名，上传到七牛云存储的。
在 init 的时候赋值本身没问题，但是重复上传一个文件名，我不太理解？
放在 upload 里面是因为上传的时候才有指定文件名的需求吧。
你可以说说你的想法

**Comment by julyL** [comment]
由于我的项目中,  七牛上传token是通过后台接口返回的，并且只有一次有效性，每次上传都需要init一遍... 而且我项目中的key是和token一起返回的，在init中设置key会比较方便

**Comment by gpake** [comment]
明白了，这样的话，在 upload 中直接带着参数应该是更符合逻辑的操作吧？
upload 可以附加options，upload 中附加的 options 会和 init 的时候一样被 sdk 更新，包括你需要的upToken，但是 key 不会。
不妨试一下？
