### ISSUE TITLE
能用，特此感谢下

### ISSUE THREAD

**Issue by 1c7** [gpake/qiniu-wxapp-sdk#52]
照着 https://www.diycode.cc/topics/583 帖子里做。
导入 qiniuUploader.js 文件。以及写一些地址配置（微信小程序后台的 uploadFile 地址）
很快就搞好了。

![image](https://user-images.githubusercontent.com/1804755/46869551-cf010b80-ce5e-11e8-9ca9-415dfad4e48c.png)

感谢。
（此 issue 读后可关闭）

**Comment by gpake** [comment]
很高兴能帮到你
