### ISSUE TITLE
获取uptoken的接口不需要鉴权么？

### ISSUE THREAD

**Issue by jamain** [gpake/qiniu-wxapp-sdk#53]
我看getQiniuToken里面请求qiniuUploadTokenURL接口并没有加任何参数，而且直接通过前段js请求，不是很容易会被别人拿到uptoken? 然后同样利用uptoken上传文件？
感觉这里有点问题，请支教

**Comment by gpake** [comment]
1. 如果需要鉴权，那么可以自己请求后通过`init`或 `upload`方法传入，这里的初衷是提供一个方便的入口。
2. 利用 https 可以让接口安全一些。
3. 另外，如果有盗用 uptoken 的行为，通过七牛的用量情况应该可以观察到，但是我不确定把自己的数据存在别人 bucket 里这种行为有多少好处，而且如果可以拦截获取你的 uptoken，那鉴权是不是也一样会被拦截掉？

**Comment by jamain** [comment]
刚开始接触小程序，也不太懂。是不是可以利用小程序云开发中的云函数来获取token，调用云函数貌似微信会自动鉴权的，这样应该就不会被人截获uptoken了

**Comment by gpake** [comment]
在我的理解来看，你是需要保障七牛 token 的安全性。
在此基础上，有几种方案
1. 可以吧图片直接丢给你持有的服务器，这样 uptoken 就只在你的服务器上存在，不会被截获
2. token 可以设置有效期，貌似可以设置一次有效，可以考虑只使用这样的一次性 token，来提升安全性
3. 我对云函数不特别了解，但是看介绍，应该也是需要利用上述思路才可以保障安全
