### ISSUE TITLE
上传图片后，七牛返回的imageURL打开后是{"error":"Document not found"}

### ISSUE THREAD

**Issue by lenxuelenxue** [gpake/qiniu-wxapp-sdk#55]
上传图片后，七牛返回的imageURL打开后是{"error":"Document not found"}，不能打开图片

**Comment by gpake** [comment]
看看 bucket 里有没有？

**Comment by lenxuelenxue** [comment]
是域名的问题。

**Comment by TSnowRock** [comment]
如果使用bucket域名上传文件之后会出现 {"error":"Document not found"}  而 uploadFile 不是支持bucket域名么？

**Comment by gpake** [comment]
我晚上回去修一下🤣，你可以先自己更新一下 base 域名

**Comment by gpake** [comment]
@lenxuelenxue @JiaXueYan b546064c775f0231898d8bfa2f219f786aab3d37 已经修复，请更新使用
