### ISSUE TITLE
上传图片携带数据，如putExtra的params？

### ISSUE THREAD

**Issue by HuangZhouHui** [gpake/qiniu-wxapp-sdk#57]
微信小程序上传图片的时候，需要带一些参数，类似于javascriptSDK的putExtra参数的params，放置自定义变量，应该怎么写？

**Comment by gpake** [comment]
小程序的上传文件接口似乎只可以在 header 中添加参数，这个 sdk 暂时还不支持这样的写法。
如果是通用的 header，可以考虑统一封装一下微信的接口，然后修改 sdk 中的上传接口。
