### ISSUE TITLE
是否有做防止重复上传的检测？

### ISSUE THREAD

**Issue by awong1900** [gpake/qiniu-wxapp-sdk#62]
>关于上传文件名
如果在上传的时候没有指定文件 key，会使用 wx.chooesImage 得到的tmp filePath作为文件的 key。例如：tmp_xxxxxxx.jpg

>https://developer.qiniu.com/kodo/kb/1365/how-to-avoid-the-users-to-upload-files-with-the-same-key

这里的文档显示官方已经做了避免重复文件的功能，只要不取key的名字即可。我们是否可以改下这里，设置key为空即为空，不用临时文件名。这样上传文件命名用hash命名，避免重复上传。

**Comment by awong1900** [comment]
用hash名字做为文件名字的例子：https://cnodejs.org 社区

**Comment by gpake** [comment]
可以，找个时间加一下，需要考虑一下 api 怎么设计。

**Comment by awong1900** [comment]
这么做的有个缺点是没有后缀名。 要做全一点就要自己生成hash名字加图片后缀了。要引入七牛那个hash库。

**Comment by gpake** [comment]
必然的，所以需要你知道这个 url 到底应该怎么处理。
不过微信的 hash 无法避免重复图片。
但是引入一个专门的 hash 库用做命名感觉又有些累赘。
看看是不是可以封装一下七牛用的 hash 方法，放在单独的库。

**Comment by awong1900** [comment]
如果是针对七牛上传的库，个人认为需要加上七牛的hash方法。 这样库的功能就比较完善了。
