### ISSUE TITLE
uptokenURL  不能取到服务器的生成的token

### ISSUE THREAD

**Issue by snow611** [gpake/qiniu-wxapp-sdk#64]
{"uptoken":"6KFuKgg2Gl48-QK6mbJ2SDvXh0pW4NGqhh********DkyNTQ3NX0="}
这是我服务器生成的 token

function initQiniu() {
  var options = {
    region: 'SCN', // 华南区
    uptokenURL: 'http://*/api/qiniutoken',
  这是小程序中设置的uptokenURL
上传图片会提示：
qiniuUploader cannot get your token, please check the uptokenURL or server

但是我用服务器取的token 直接设置到小程序中的  uptoken: '6KFuKgg2Gl48-QK6mbJ2SDvXh0pW4**********DkyMjM2M30=',

这样可以正确的上传！！！
请问这是怎么回事啊？

**Comment by gpake** [comment]
建议可以更新一下问题的原因和解决办法供他人参考，多谢
