### ISSUE TITLE
uptokenURL 设置后无效

### ISSUE THREAD

**Issue by snow611** [gpake/qiniu-wxapp-sdk#66]
控制台的打印
![图片](https://user-images.githubusercontent.com/6668345/59026450-ffcc0000-8888-11e9-91c8-735101618e42.png)

服务器地址生成的json
![图片](https://user-images.githubusercontent.com/6668345/59026548-428dd800-8889-11e9-8e7e-7576338f3594.png)

如果直接用服务器生成的token ，放到小程序中可以正常上传。
请问这是怎么回事

**Comment by gpake** [comment]
因为从url直接取token的路径比较傻，所以需要你检查一下返回的数据path是否需要修改。
默认取值路径是response.data.uptoken

**Comment by snow611** [comment]
> 
> 因为从url直接取token的路径比较傻，所以需要你检查一下返回的数据path是否需要修改。 默认取值路径是response.data.uptoken
> […](#)
> 在 2019年6月6日，18:32，yxfCode ***@***.***> 写道： 控制台的打印 服务器地址生成的json 如果直接用服务器生成的token ，放到小程序中可以正常上传。 请问这是怎么回事 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

解决了，原来要修改sdk 中的getQiniuToken函数，把res.data序列化一下就拿到了
