### ISSUE TITLE
之前使用过这个sdk没有问题，最近总提示`incorrect region, please use up-z0.qiniu.com`错误，并且返回的地址也是undefined

### ISSUE THREAD

**Issue by 469306621** [gpake/qiniu-wxapp-sdk#7]
之前使用过这个sdk没有问题，最近总提示如下错误，并且返回的地址也是undefined
error:"incorrect region, please use up-z0.qiniu.com"
imageURL:"https://nst-img.yunfeng365.com/undefined"

**Comment by 469306621** [comment]
代码没有改动过，之前能用，现在报错！

**Comment by 469306621** [comment]
upToken 的问题，合并代码的时候没有看到，不好意思，已更正！！！

**Comment by lenxuelenxue** [comment]
能说一下是怎么解决的吗？我也遇到这个问题了
