### ISSUE TITLE
一定需要后台服务器吗

### ISSUE THREAD

**Issue by tighunt** [gpake/qiniu-wxapp-sdk#9]
没有后台服务器如何使用，拿到uptoken

**Comment by gpake** [comment]
以七牛的建议来说，配合服务器分发 token 更安全一些，uptoken 的生成代码可以参考[七牛上传 token 文档](https://developer.qiniu.com/kodo/manual/1208/upload-token) 或者我朋友写的 [tiny-qiniu](https://github.com/die-welle/tiny-qiniu/blob/master/src/index.js)
